- hosts: RHEL
  remote_user: ec2-user
  gather_facts: false
  tasks:

   - name: Install Python
     yum:
        name: python3
        state: latest
        use_backend: dnf
   - name: Install Python-Pip
     yum:
        name: python-pip
        state: latest
        use_backend: dnf
