- hosts: RHEL
  remote_user: ec2-user
  gather_facts: false
  tasks:

   - name: Install Python
     yum:
        name: python3
        state: latest
        use_backend: dnf
   - name: Install Python-Pip
     yum:
        name: python3-pip
        state: latest
        use_backend: dnf
   - name: Create a new symbolic link
     file:
       src: /bin/pip3
       dest: /usr/bin/pip
       owner: root
       group: root
       state: link
   - name: Add a line to a file if the file does not exist, without passing regexp
     lineinfile:
       path: $HOME/.bashrc
       line: "export $PATH=/usr/bin:$PATH"
       create: yes
